-- Inserción masiva de ejercicios globales
INSERT INTO public.exercises (
  name, slug, description, main_muscle_group, secondary_muscles,
  equipment, exercise_type, instructions, technique_tips, difficulty_level, is_custom
)
VALUES
(
    'Press banca con barra',
    'press-banca-barra',
    'Básico y compuesto por excelencia para fuerza y masa en pectorales.',
    'pecho',
    ARRAY['triceps','hombros']::TEXT[],
    'barra',
    'compuesto',
    ARRAY['Acuéstate sobre el banco plano con los ojos bajo la barra.','Agarra la barra a un ancho ligeramente mayor a hombros.','Retrae escápulas y apoya pies firmes.','Baja controladamente a la parte media del pecho.','Empuja extendiendo brazos sin bloquear codos bruscamente.']::TEXT[],
    'Mantén escápulas retraídas y glúteos pegados al banco.',
    'intermedio',
    false
  ),
(
    'Press inclinado con barra',
    'press-inclinado-barra',
    'Énfasis en el haz clavicular (pecho superior).',
    'pecho',
    ARRAY['hombros','triceps']::TEXT[],
    'barra',
    'compuesto',
    ARRAY['Ajusta el banco a 30-45 grados.','Baja la barra de forma controlada hacia la clavícula.','Empuja con fuerza hasta posición inicial.']::TEXT[],
    'Evita inclinar a más de 45° para no fatigar el hombro anterior.',
    'intermedio',
    false
  ),
(
    'Press con mancuernas',
    'press-mancuernas',
    'Mayor rango de movimiento y corrección de asimetrías.',
    'pecho',
    ARRAY['triceps','hombros']::TEXT[],
    'mancuernas',
    'compuesto',
    ARRAY['Túmbate en el banco con mancuernas al costado del pecho.','Baja sintiendo el estiramiento pectoral.','Empuja acercando mancuernas sin chocarlas.']::TEXT[],
    'Controla la fase excéntrica en 2-3 segundos.',
    'intermedio',
    false
  ),
(
    'Press inclinado con mancuernas',
    'press-inclinado-mancuernas',
    'Enfoque clavicular con libertad articular para muñecas y codos.',
    'pecho',
    ARRAY['hombros','triceps']::TEXT[],
    'mancuernas',
    'compuesto',
    ARRAY['Banco a 30 grados, desciende controlando los codos a 45 grados.','Empuja contrayendo la porción alta del pecho.']::TEXT[],
    'Ángulo de 30° es óptimo.',
    'intermedio',
    false
  ),
(
    'Aperturas con mancuernas',
    'aperturas-mancuernas',
    'Aislamiento para estirar las fibras pectorales bajo tensión.',
    'pecho',
    ARRAY['hombros']::TEXT[],
    'mancuernas',
    'aislamiento',
    ARRAY['Abre los brazos en un arco amplio con codos ligeramente flexionados.','Cierra contrayendo fuertemente los pectorales.']::TEXT[],
    'No bajes de la línea de los hombros si sientes molestia articular.',
    'principiante',
    false
  ),
(
    'Pec deck / Contractor',
    'pec-deck',
    'Máquina guiada con tensión constante en todo el recorrido.',
    'pecho',
    ARRAY['hombros']::TEXT[],
    'maquina',
    'aislamiento',
    ARRAY['Junta los brazos al centro manteniendo 1s de contracción pico.','Regresa lento controlando las placas.']::TEXT[],
    'Empuja con codos y pecho, no tirando de las manos.',
    'principiante',
    false
  ),
(
    'Fondos para pecho (Dips)',
    'fondos-pecho',
    'Peso corporal con inclinación frontal para pectoral inferior.',
    'pecho',
    ARRAY['triceps','hombros']::TEXT[],
    'peso_corporal',
    'compuesto',
    ARRAY['Inclina el torso 30° hacia adelante en paralelas.','Baja a 90° de flexión y empuja fuerte.']::TEXT[],
    'Inclina el cuerpo al frente para enfocar pecho.',
    'avanzado',
    false
  ),
(
    'Cruce de poleas',
    'cruce-poleas',
    'Aislamiento continuo con cables para bombeo y congestión.',
    'pecho',
    ARRAY['hombros']::TEXT[],
    'polea',
    'aislamiento',
    ARRAY['Desde polea media o alta, cruza las manos al frente y abajo.','Siente la compresión pectoral en cada repetición.']::TEXT[],
    'Mantén codos fijos y aprieta 1 segundo al cruzar.',
    'intermedio',
    false
  ),
(
    'Dominadas',
    'dominadas',
    'Tracción vertical fundamental para amplitud de dorsal ancho.',
    'espalda',
    ARRAY['biceps','core']::TEXT[],
    'peso_corporal',
    'compuesto',
    ARRAY['Cuélgate con agarre prono a ancho superior a hombros.','Tracciona con los dorsales llevando el pecho hacia la barra.','Supera con la barbilla y baja con control total.']::TEXT[],
    'Evita balanceo y concéntrate en tirar con la espalda.',
    'intermedio',
    false
  ),
(
    'Jalón al pecho en polea',
    'jalon-pecho',
    'Tracción vertical guiada para dorsales con peso regulable.',
    'espalda',
    ARRAY['biceps']::TEXT[],
    'polea',
    'compuesto',
    ARRAY['Fija las piernas, toma la barra ancha y baja hacia el esternón superior.','Extiende los dorsales arriba al regresar.']::TEXT[],
    'Lleva los codos hacia las costillas.',
    'principiante',
    false
  ),
(
    'Remo con barra',
    'remo-barra',
    'Tracción horizontal pesada para grosor y densidad de espalda.',
    'espalda',
    ARRAY['biceps','core']::TEXT[],
    'barra',
    'compuesto',
    ARRAY['Inclina torso a 45° con columna neutra.','Tracciona la barra hacia el ombligo contrayendo escápulas.','Baja con control sin perder la postura.']::TEXT[],
    'Activa el core para no cargar la zona lumbar.',
    'intermedio',
    false
  ),
(
    'Remo con mancuerna a una mano',
    'remo-mancuerna',
    'Trabajo unilateral con gran recorrido y estabilidad lumbar.',
    'espalda',
    ARRAY['biceps']::TEXT[],
    'mancuernas',
    'compuesto',
    ARRAY['Apoya rodilla y mano en banco plano.','Tira la mancuerna en diagonal hacia la cadera con el codo.','Estira el dorsal al bajar.']::TEXT[],
    'No rotes el torso excesivamente.',
    'principiante',
    false
  ),
(
    'Remo sentado en polea (Gironda)',
    'remo-gironda',
    'Remo en polea baja para zona media de trapecios y romboides.',
    'espalda',
    ARRAY['biceps']::TEXT[],
    'polea',
    'compuesto',
    ARRAY['Espalda recta, tracciona el maneral V hacia el abdomen.','Aprieta escápulas y regresa despacio.']::TEXT[],
    'No balancees el cuerpo bruscamente.',
    'principiante',
    false
  ),
(
    'Pullover en polea alta',
    'pullover-polea-alta',
    'Aislamiento de dorsales sin fatiga de bíceps.',
    'espalda',
    ARRAY['core','triceps']::TEXT[],
    'polea',
    'aislamiento',
    ARRAY['Brazos casi rectos, lleva la barra hacia los muslos en un arco.','Aprieta dorsales y regresa a la altura de ojos.']::TEXT[],
    'Tira con los codos manteniendo codos semi-rígidos.',
    'intermedio',
    false
  ),
(
    'Peso muerto convencional',
    'peso-muerto-convencional',
    'Fuerza total y masa para erectores espinales, glúteos y trapecios.',
    'espalda',
    ARRAY['piernas','core']::TEXT[],
    'barra',
    'compuesto',
    ARRAY['Pies al ancho de cadera, agarra la barra por fuera de piernas.','Espalda recta, empuja el piso extendiendo cadera y rodillas.','Ponte erguido y baja pegado a los muslos.']::TEXT[],
    'Nunca curves la espalda baja bajo carga.',
    'avanzado',
    false
  ),
(
    'Press militar con barra',
    'press-militar-barra',
    'Empuje vertical estricto para hombros y fuerza general de tren superior.',
    'hombros',
    ARRAY['triceps','core']::TEXT[],
    'barra',
    'compuesto',
    ARRAY['Barra en clavículas, glúteos y abdomen apretados.','Empuja la barra verticalmente por encima de la cabeza.','Bloquea brazos arriba y baja con control.']::TEXT[],
    'No arquees la zona lumbar al subir.',
    'intermedio',
    false
  ),
(
    'Press sentado con mancuernas',
    'press-hombros-mancuernas',
    'Aislamiento de deltoides con respaldo y rango independiente.',
    'hombros',
    ARRAY['triceps']::TEXT[],
    'mancuernas',
    'compuesto',
    ARRAY['Mancuernas a la altura de las orejas en banco a 85 grados.','Presiona hacia arriba en arco convergente.','Desciende controladamente sin chocar las mancuernas.']::TEXT[],
    'Mantén tensión continua sin relajar abajo.',
    'principiante',
    false
  ),
(
    'Elevaciones laterales',
    'elevaciones-laterales',
    'El ejercicio clave para dar amplitud en V con deltoides laterales.',
    'hombros',
    ARRAY['trapecio']::TEXT[],
    'mancuernas',
    'aislamiento',
    ARRAY['Eleva mancuernas hacia los lados guiando con codos hasta altura de hombros.','Baja resistiendo el peso en 2 segundos.']::TEXT[],
    'Piensa en empujar las paredes hacia los lados con los codos.',
    'principiante',
    false
  ),
(
    'Pájaros / Deltoides posterior',
    'pajaros-posteriores',
    'Aislamiento de deltoides posterior para equilibrio y salud de hombro.',
    'hombros',
    ARRAY['espalda']::TEXT[],
    'mancuernas',
    'aislamiento',
    ARRAY['Inclina torso hacia adelante con espalda recta casi horizontal.','Eleva las mancuernas a los lados contrayendo la parte posterior de hombros.']::TEXT[],
    'Usa pesos moderados sin impulsos del torso.',
    'intermedio',
    false
  ),
(
    'Face pull en polea',
    'face-pull',
    'Esencial para manguito rotador, trapecio y deltoides posterior.',
    'hombros',
    ARRAY['espalda']::TEXT[],
    'polea',
    'aislamiento',
    ARRAY['Cuerda a la altura de los ojos, tira hacia la frente separando manos.','Rota externamente los hombros contrayendo 1s atrás.']::TEXT[],
    'Codos altos y muñecas hacia atrás.',
    'principiante',
    false
  ),
(
    'Curl de bíceps con barra',
    'curl-barra',
    'Sobrecarga principal para ambas cabezas del bíceps braquial.',
    'biceps',
    ARRAY['antebrazos']::TEXT[],
    'barra',
    'aislamiento',
    ARRAY['Codos pegados a costillas, sube la barra flexionando codos.','Aprieta en la cima y desciende lento.']::TEXT[],
    'Sin balanceo de cadera ni tirones.',
    'principiante',
    false
  ),
(
    'Curl con mancuernas alterno',
    'curl-mancuernas-alterno',
    'Supinación activa para máxima contracción del bíceps.',
    'biceps',
    ARRAY['antebrazos']::TEXT[],
    'mancuernas',
    'aislamiento',
    ARRAY['Sube la mancuerna girando la palma hacia arriba (supinación).','Baja controlando y alterna de brazo.']::TEXT[],
    'Comienza a supinar desde el primer tercio del movimiento.',
    'principiante',
    false
  ),
(
    'Curl martillo',
    'curl-martillo',
    'Trabaja braquial anterior y braquiorradial para engrosar el brazo.',
    'biceps',
    ARRAY['antebrazos']::TEXT[],
    'mancuernas',
    'aislamiento',
    ARRAY['Palmas enfrentadas en todo momento (agarre neutro).','Flexiona llevando mancuernas hacia hombros sin rotar muñecas.']::TEXT[],
    'Hombros firmes y codos bloqueados en posición.',
    'principiante',
    false
  ),
(
    'Curl inclinado con mancuernas',
    'curl-inclinado',
    'Estiramiento máximo de la cabeza larga en banco inclinado.',
    'biceps',
    ARRAY['antebrazos']::TEXT[],
    'mancuernas',
    'aislamiento',
    ARRAY['Acuéstate en banco a 45-60 grados con brazos colgando.','Haz curl sin adelantar los codos.']::TEXT[],
    'Siente el estiramiento profundo antes de cada repetición.',
    'intermedio',
    false
  ),
(
    'Curl predicador en banco Scott',
    'curl-predicador',
    'Aisla el bíceps imposibilitando cualquier impulso del cuerpo.',
    'biceps',
    ARRAY['antebrazos']::TEXT[],
    'barra',
    'aislamiento',
    ARRAY['Brazos apoyados en la almohadilla, sube hasta la vertical.','Baja hasta casi extensión completa sin bloquear codos.']::TEXT[],
    'No despegues los codos de la almohadilla.',
    'intermedio',
    false
  ),
(
    'Press francés con barra Z',
    'press-frances-barra-z',
    'Desarrollo masivo de cabeza medial y larga del tríceps.',
    'triceps',
    ARRAY['pecho']::TEXT[],
    'barra',
    'aislamiento',
    ARRAY['Tumbado en banco plano con barra Z en alto.','Flexiona solo codos bajando la barra a la coronilla o trasnuca.','Extiende los antebrazos contrayendo tríceps.']::TEXT[],
    'Mantén codos cerrados hacia adentro sin abrir hacia afuera.',
    'intermedio',
    false
  ),
(
    'Extensión de tríceps en polea (Pushdown)',
    'pushdown-polea',
    'Aislamiento constante y congestión para cabeza lateral.',
    'triceps',
    ARRAY[]::TEXT[],
    'polea',
    'aislamiento',
    ARRAY['Codos pegados a costillas, empuja la barra o cuerda hacia abajo.','Extiende por completo y regresa hasta ángulo de 90°.']::TEXT[],
    'Los codos deben quedar fijos como bisagras.',
    'principiante',
    false
  ),
(
    'Extensión trasnuca con mancuerna',
    'extension-trasnuca',
    'Máxima elongación y trabajo de la cabeza larga del tríceps.',
    'triceps',
    ARRAY[]::TEXT[],
    'mancuernas',
    'aislamiento',
    ARRAY['Sostén mancuerna con ambas manos sobre la cabeza.','Baja la mancuerna detrás de la nuca flexionando codos.','Extiende hacia arriba sin mover la espalda.']::TEXT[],
    'Codos lo más apuntados al techo posible.',
    'intermedio',
    false
  ),
(
    'Fondos para tríceps en paralelas',
    'fondos-triceps',
    'Empuje vertical con torso erguido para tríceps masivos.',
    'triceps',
    ARRAY['pecho','hombros']::TEXT[],
    'peso_corporal',
    'compuesto',
    ARRAY['Cuerpo vertical en barras paralelas con codos cerrados.','Baja a 90° y empuja extendiendo codos con fuerza.']::TEXT[],
    'Cuerpo recto para focalizar tríceps (no inclinar el torso).',
    'avanzado',
    false
  ),
(
    'Sentadilla trasera con barra',
    'sentadilla-trasera',
    'El pilar fundamental de la fuerza y desarrollo del tren inferior.',
    'piernas',
    ARRAY['core','gluteos']::TEXT[],
    'barra',
    'compuesto',
    ARRAY['Barra en trapecios, pies a ancho de hombros con puntas ligeramente abiertas.','Rompe paralelo bajando con control llevando rodillas en dirección de puntas.','Empuja el suelo firmemente para subir a posición inicial.']::TEXT[],
    'Talones pegados al piso y pecho erguido.',
    'avanzado',
    false
  ),
(
    'Sentadilla frontal con barra',
    'sentadilla-frontal',
    'Mayor verticalidad del torso y enfoque directo en cuádriceps y core.',
    'piernas',
    ARRAY['core']::TEXT[],
    'barra',
    'compuesto',
    ARRAY['Barra descansando en deltoides anteriores con codos altos.','Desciende profundo manteniendo el torso totalmente vertical.','Empuja el suelo ascendiendo con codos apuntando al frente.']::TEXT[],
    'Mantén los codos altos para que la barra no ruede hacia adelante.',
    'avanzado',
    false
  ),
(
    'Prensa de piernas 45°',
    'prensa-piernas-45',
    'Gran sobrecarga para cuádriceps y glúteos con bajo estrés espinal.',
    'piernas',
    ARRAY['gluteos']::TEXT[],
    'maquina',
    'compuesto',
    ARRAY['Espalda y glúteos pegados al respaldo.','Baja la plataforma hasta flexión profunda sin despegar el coxis.','Empuja sin bloquear las rodillas en la cima.']::TEXT[],
    'Nunca bloquees las rodillas por completo.',
    'principiante',
    false
  ),
(
    'Peso muerto rumano (RDL)',
    'peso-muerto-rumano',
    'Máxima tensión e hipertrofia para isquiotibiales y glúteos.',
    'piernas',
    ARRAY['espalda','gluteos']::TEXT[],
    'barra',
    'compuesto',
    ARRAY['Rodillas semi-flexionadas pero fijas.','Empuja la cadera hacia atrás bajando la barra rozando piernas.','Extiende cadera con fuerza de glúteos para volver erguido.']::TEXT[],
    'Espalda totalmente recta; el movimiento es de bisagra de cadera.',
    'intermedio',
    false
  ),
(
    'Extensión de cuádriceps',
    'extension-cuadriceps',
    'Aislamiento para acortamiento máximo del cuádriceps.',
    'piernas',
    ARRAY[]::TEXT[],
    'maquina',
    'aislamiento',
    ARRAY['Almohadilla en tibias bajas, extiende piernas hacia arriba.','Aprieta 1 segundo arriba y baja en 2-3 segundos.']::TEXT[],
    'Sujeta firmemente las agarraderas laterales.',
    'principiante',
    false
  ),
(
    'Curl femoral tumbado',
    'curl-femoral-tumbado',
    'Flexión de rodilla directa para isquiotibiales.',
    'piernas',
    ARRAY[]::TEXT[],
    'maquina',
    'aislamiento',
    ARRAY['Boca abajo con almohadilla tras tobillos.','Flexiona rodillas acercando talones a glúteos.','Baja controlando sin soltar el peso de golpe.']::TEXT[],
    'Mantén la pelvis pegada al banco.',
    'principiante',
    false
  ),
(
    'Hip thrust con barra',
    'hip-thrust',
    'El ejercicio de mayor activación y carga para glúteos.',
    'piernas',
    ARRAY['gluteos']::TEXT[],
    'barra',
    'compuesto',
    ARRAY['Espalda media en borde del banco, barra acolchada en pelvis.','Empuja talones extendiendo cadera hasta quedar horizontal.','Aprieta glúteos 1s arriba con mentón recogido.']::TEXT[],
    'Mira siempre al frente para no arquear cuello ni lumbares.',
    'intermedio',
    false
  ),
(
    'Zancadas con mancuernas',
    'zancadas-mancuernas',
    'Trabajo dinámico unilateral para fuerza de piernas y estabilidad.',
    'piernas',
    ARRAY['gluteos','core']::TEXT[],
    'mancuernas',
    'compuesto',
    ARRAY['Paso amplio adelante flexionando ambas rodillas a 90°.','Empuja con pierna delantera para regresar erguido.']::TEXT[],
    'Torso firme sin tambaleos laterales.',
    'intermedio',
    false
  ),
(
    'Sentadilla búlgara',
    'sentadilla-bulgara',
    'Gran estímulo unilateral en banco para glúteo y cuádriceps.',
    'piernas',
    ARRAY['gluteos']::TEXT[],
    'mancuernas',
    'compuesto',
    ARRAY['Pie trasero elevado en banco, desciende la rodilla al suelo.','Sube empujando desde el talón delantero.']::TEXT[],
    'Inclina levemente el torso al frente para activar glúteo.',
    'avanzado',
    false
  ),
(
    'Elevación de talones / Gemelos',
    'gemelos-de-pie',
    'Estiramiento y contracción completa para gemelos.',
    'piernas',
    ARRAY[]::TEXT[],
    'maquina',
    'aislamiento',
    ARRAY['Punta de pies en plataforma, baja talones al máximo estiramiento.','Ponte de puntillas al tope y pausa 1s.']::TEXT[],
    'Pausa en el fondo para evitar el rebote elástico del tendón.',
    'principiante',
    false
  ),
(
    'Crunch en polea alta',
    'crunch-polea',
    'Sobrecarga progresiva con peso para recto abdominal.',
    'core',
    ARRAY[]::TEXT[],
    'polea',
    'aislamiento',
    ARRAY['Arrodillado con cuerda tras nuca, enrolla la columna hacia los muslos.','Aprieta abdomen abajo y regresa con control.']::TEXT[],
    'Flexiona la columna, no te sientes sobre los talones.',
    'intermedio',
    false
  ),
(
    'Elevaciones de piernas colgado',
    'elevaciones-piernas',
    'Excelente para abdomen bajo y flexores de cadera.',
    'core',
    ARRAY['antebrazos']::TEXT[],
    'peso_corporal',
    'aislamiento',
    ARRAY['Colgado de barra, eleva piernas flexionando la pelvis hacia el pecho.','Baja sin balanceos.']::TEXT[],
    'Retroverte la pelvis para activar los abdominales.',
    'avanzado',
    false
  ),
(
    'Plancha isométrica',
    'plancha',
    'Fuerza estática y estabilidad para todo el cinturón abdominal.',
    'core',
    ARRAY['gluteos','hombros']::TEXT[],
    'peso_corporal',
    'aislamiento',
    ARRAY['Sobre antebrazos y puntas de pies formando una línea recta.','Aprieta glúteos y ombligo hacia adentro.']::TEXT[],
    'No dejes caer la cadera ni la subas en pirámide.',
    'principiante',
    false
  ),
(
    'Rueda abdominal (Ab wheel)',
    'rueda-abdominal',
    'Anti-extensión máxima para abdominales de acero.',
    'core',
    ARRAY['espalda','triceps']::TEXT[],
    'otro',
    'aislamiento',
    ARRAY['De rodillas, rueda hacia adelante extendiendo el cuerpo.','Tira con el abdomen para regresar a la posición inicial.']::TEXT[],
    'Aprieta glúteos para evitar dolor lumbar.',
    'avanzado',
    false
  )
ON CONFLICT DO NOTHING;
